
version: '3.8'
services:
  python-server:
    build:
      context: ./python-server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./python-server/src:/app/src
    command: python -u src/main.py

  js-express-server:
    build: ./js-express-server
    ports:
      - "8001:8001"
    volumes:
      - ./js-express-server:/app
    command: yarn start
